const T_CONFIG = struct {
    USE_LLVM: bool,
    INCLUDE_SDL: bool,
    SDL_EMSCRIPTEN_PTHREADS: bool,
    SDL_INSTALL_BUILD_CONFIG_H: bool,
    SDL_USER_HANDLES_MAIN: bool,
    SDL_USER_PROVIDES_CALLBACKS: bool,
    SDL_GFX_CONTROLLER_MAX_STORAGE_REGISTERS: u32,
};
pub const CONFIG = T_CONFIG{
    .INCLUDE_SDL = true,
    .SDL_EMSCRIPTEN_PTHREADS = false,
    .SDL_GFX_CONTROLLER_MAX_STORAGE_REGISTERS = 64,
    .SDL_INSTALL_BUILD_CONFIG_H = false,
    .SDL_USER_HANDLES_MAIN = true,
    .SDL_USER_PROVIDES_CALLBACKS = true,
    .USE_LLVM = false,
};
