pub const PointOrientation = enum {
    COLINEAR,
    WINDING_CCW,
    WINDING_CW,
};

pub const AllocErrorBehavior = enum {
    ALLOCATION_ERRORS_RETURN_ERROR,
    ALLOCATION_ERRORS_PANIC,
    ALLOCATION_ERRORS_ARE_UNREACHABLE,
};

pub const GrowthModel = enum {
    GROW_EXACT_NEEDED,
    GROW_EXACT_NEEDED_WITH_ATOMIC_PADDING,
    GROW_BY_100_PERCENT,
    GROW_BY_100_PERCENT_WITH_ATOMIC_PADDING,
    GROW_BY_50_PERCENT,
    GROW_BY_50_PERCENT_WITH_ATOMIC_PADDING,
    GROW_BY_25_PERCENT,
    GROW_BY_25_PERCENT_WITH_ATOMIC_PADDING,
};

pub const SortAlgorithm = enum {
    // BUBBlE_SORT,
    // HEAP_SORT,
    QUICK_SORT_PIVOT_FIRST,
    QUICK_SORT_PIVOT_MIDDLE,
    QUICK_SORT_PIVOT_LAST,
    QUICK_SORT_PIVOT_RANDOM,
    QUICK_SORT_PIVOT_MEDIAN_OF_3,
    QUICK_SORT_PIVOT_MEDIAN_OF_3_RANDOM,
};
